/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.clonadas;

import java.util.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Area;
import modelo.Http;
import org.json.JSONArray;
import modelo.UnidadMedida;
import org.json.JSONObject;

/**
 *
 * @author Felipe
 */
public class VistaPruebas extends javax.swing.JFrame {

    private DefaultTableModel modelTabla;
    private DefaultComboBoxModel modelUnidades;
    private DefaultComboBoxModel modelArea;
    private final String nameRecurso = "/pruebas";
    private Http peticion;
    public VistaPruebas() {
        initComponents();
        extrasSetup();
        inicializarComponentes();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTitulo = new javax.swing.JPanel();
        jLabelTituloVentana = new javax.swing.JLabel();
        jPanelAcciones = new javax.swing.JPanel();
        jButtonGrabar = new javax.swing.JButton();
        jButtonActualizar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jPanelContenedorTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePruebas = new javax.swing.JTable();
        jPanelInfo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldTitulo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldPrecio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldLimSup = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldLimInf = new javax.swing.JTextField();
        jPanelInfoExtra = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxArea = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxUnidad = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelTitulo.setBackground(new java.awt.Color(255, 255, 255));
        jPanelTitulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelTitulo.setLayout(new java.awt.BorderLayout());

        jLabelTituloVentana.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelTituloVentana.setText("LAB: PRUEBA");
        jPanelTitulo.add(jLabelTituloVentana, java.awt.BorderLayout.CENTER);

        jPanelAcciones.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelAcciones.setLayout(new java.awt.GridLayout(3, 1));

        jButtonGrabar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonGrabar.setText("Guardar");
        jButtonGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGrabarActionPerformed(evt);
            }
        });
        jPanelAcciones.add(jButtonGrabar);

        jButtonActualizar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonActualizar.setText("Actualizar");
        jButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarActionPerformed(evt);
            }
        });
        jPanelAcciones.add(jButtonActualizar);

        jButtonEliminar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        jPanelAcciones.add(jButtonEliminar);

        jPanelContenedorTabla.setBackground(new java.awt.Color(255, 255, 255));
        jPanelContenedorTabla.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelContenedorTabla.setLayout(new java.awt.BorderLayout());

        jTablePruebas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTablePruebas);

        jPanelContenedorTabla.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanelInfo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelInfo.setLayout(new java.awt.GridLayout(5, 2));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("TÍTULO:");
        jPanelInfo.add(jLabel2);

        jTextFieldTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldTitulo.setText("Prueba1");
        jPanelInfo.add(jTextFieldTitulo);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("PRECIO:");
        jPanelInfo.add(jLabel3);

        jTextFieldPrecio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldPrecio.setText("10");
        jPanelInfo.add(jTextFieldPrecio);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("LÍMITE SUPERIOR:");
        jPanelInfo.add(jLabel5);

        jTextFieldLimSup.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldLimSup.setText("1");
        jPanelInfo.add(jTextFieldLimSup);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("LÍMITE INFERIOR:");
        jPanelInfo.add(jLabel6);

        jTextFieldLimInf.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldLimInf.setText("100");
        jPanelInfo.add(jTextFieldLimInf);

        jPanelInfoExtra.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelInfoExtra.setLayout(new java.awt.GridLayout(2, 2));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("ÁREA:");
        jPanelInfoExtra.add(jLabel4);

        jPanelInfoExtra.add(jComboBoxArea);

        jButton1.setText("Areas");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanelInfoExtra.add(jButton1);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("UNIDAD:");
        jPanelInfoExtra.add(jLabel7);

        jPanelInfoExtra.add(jComboBoxUnidad);

        jButton2.setText("Unidades");
        jPanelInfoExtra.add(jButton2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelContenedorTabla, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanelInfoExtra, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelAcciones, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelInfoExtra, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelAcciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelContenedorTabla, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGrabarActionPerformed
       grabar();
    }//GEN-LAST:event_jButtonGrabarActionPerformed

    private void jButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarActionPerformed
        actualizar();
    }//GEN-LAST:event_jButtonActualizarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        eliminar();
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        VistaAreas areas=new VistaAreas();
        areas.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPruebas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPruebas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPruebas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPruebas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPruebas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    public javax.swing.JButton jButtonActualizar;
    public javax.swing.JButton jButtonEliminar;
    public javax.swing.JButton jButtonGrabar;
    private javax.swing.JComboBox<UnidadMedida> jComboBoxArea;
    private javax.swing.JComboBox<Area> jComboBoxUnidad;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelTituloVentana;
    private javax.swing.JPanel jPanelAcciones;
    private javax.swing.JPanel jPanelContenedorTabla;
    private javax.swing.JPanel jPanelInfo;
    private javax.swing.JPanel jPanelInfoExtra;
    private javax.swing.JPanel jPanelTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTablePruebas;
    private javax.swing.JTextField jTextFieldLimInf;
    private javax.swing.JTextField jTextFieldLimSup;
    private javax.swing.JTextField jTextFieldPrecio;
    private javax.swing.JTextField jTextFieldTitulo;
    // End of variables declaration//GEN-END:variables
    private void extrasSetup() {
        this.setLocationRelativeTo(null);
    }

    private void inicializarComponentes() {
        modelTabla = new DefaultTableModel();
        modelUnidades = new DefaultComboBoxModel();
        modelArea = new DefaultComboBoxModel();

        modelTabla.addColumn("ID");
        modelTabla.addColumn("Titulo");
        modelTabla.addColumn("Precio");
        modelTabla.addColumn("L.Inferior");
        modelTabla.addColumn("L.Superior");
        modelTabla.addColumn("Area");
        modelTabla.addColumn("Unidad");
        

        jTablePruebas.setModel(modelTabla);
        jComboBoxArea.setModel(modelArea);
        jComboBoxUnidad.setModel(modelUnidades);
        peticion=new Http();
        recuperarDatosParaTabla();
        addDataComboUnidad();
        addDataComboArea();
    }

    private void limpiarTabla() {
        int i;
        int cuantos = modelTabla.getRowCount();
        for (i = cuantos - 1; i >= 0; i--) {
            modelTabla.removeRow(i);
        }
    }

    private void recuperarDatosParaTabla() {
        limpiarTabla();
        peticion=new Http();
        String json = peticion.sendGet(nameRecurso);
        construirTabla(json);
        System.out.println(json);

    }

    private Object[] construirTabla(String json) {
        Object[] areas = new Object[7];

        JSONArray areasJSON = new JSONArray(json);

        for (int i = 0; i < areasJSON.length(); i++) {
            areas[0] = areasJSON.getJSONObject(i).get("id").toString();
            areas[1] = areasJSON.getJSONObject(i).get("titulo").toString();
            areas[2] = areasJSON.getJSONObject(i).get("precio").toString();
            areas[3] = areasJSON.getJSONObject(i).get("limiteInferior").toString();
            areas[4] = areasJSON.getJSONObject(i).get("limiteSuperior").toString();

            //areas[5] = (areasJSON.getJSONObject(i).get("area").toString()).split("\"")[0];
            var area = (JSONObject) areasJSON.getJSONObject(i).get("area");
            areas[5] = area.get("nombre").toString();

            var unidadM = (JSONObject) areasJSON.getJSONObject(i).get("unidadMedida");
            areas[6] = unidadM.get("unidadDeMedida").toString();
            //areas[6] = areasJSON.getJSONObject(i).get("unidadMedida").toString();
            modelTabla.addRow(areas);
        }
        return areas;
    }

    private void grabar() {
        if (jTextFieldTitulo.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Lleno todos los campos");
        } else {
            Map<Object, Object> data;
            data = new HashMap<>();
            data.put("titulo", this.jTextFieldTitulo.getText());
            data.put("precio", this.jTextFieldPrecio.getText());
            data.put("limiteInferior", this.jTextFieldLimInf.getText());
            data.put("limiteSuperior", this.jTextFieldLimSup.getText());

            var areaObject = (Area) this.modelArea.getSelectedItem();
            System.out.println("area:"+"{\"id\":"+areaObject.getId()+"}");
            data.put("area",areaObject.getId());
            data.put("area",areaObject.getId());
            
            
            var unidad = (UnidadMedida) this.modelUnidades.getSelectedItem();
            System.out.println("Unidad:"+ "{\"id\":"+unidad.getId()+"}");
            data.put("unidadMedida", "{\"id\":"+unidad.getId()+"}");
            
            peticion=new Http();
            peticion.sendPost(data, nameRecurso);
            recuperarDatosParaTabla();
        }

    }

    private void eliminar() {
        int identificador = this.jTablePruebas.getSelectedRow();
        if (identificador == -1) {
            JOptionPane.showMessageDialog(null, "Seleccione una fila");
        } else {
            String idArea = (String) this.jTablePruebas.getValueAt(identificador, 0);
            System.out.println("IdArea:" + idArea);
            int resp = JOptionPane.showConfirmDialog(null, "¿Esta seguro de Eliminar ?", "Alerta!", JOptionPane.YES_NO_OPTION);
            if (resp == 0) {
                //Http.sendGet("");
                JOptionPane.showMessageDialog(null, "Unidad Eliminada.");
            }
            this.jTextFieldTitulo.setText("");

            recuperarDatosParaTabla();

        }
    }

    private void actualizar() {

        int identificador = this.jTablePruebas.getSelectedRow();

        if (identificador == -1) {
            JOptionPane.showMessageDialog(null, "Seleccione una fila");
        } else {

            var index = (String) modelTabla.getValueAt(identificador, 0);
            Map<Object, Object> data;
            data = new HashMap<>();
            data.put("titulo", this.jTextFieldTitulo.getText());
            data.put("precio", this.jTextFieldPrecio.getText());
            data.put("limiteInferior", this.jTextFieldLimInf.getText());
            data.put("limiteSuperior", this.jTextFieldLimSup.getText());
            peticion.sendPost(data, nameRecurso);
            recuperarDatosParaTabla();

        }
    }

    private ArrayList<UnidadMedida> getUnidadesMedidaObjetcs() {
        var listaUM = new ArrayList<UnidadMedida>();
        String tabla = "/unidades";
        String json = peticion.sendGet(tabla);
        JSONArray areasJSON = new JSONArray(json);
        for (int i = 0; i < areasJSON.length(); i++) {
            var id = (Integer) areasJSON.getJSONObject(i).get("id");
            var valor = (String) areasJSON.getJSONObject(i).get("unidadDeMedida");
            var unidadDeMedida = new UnidadMedida(id, valor);
            listaUM.add(unidadDeMedida);

        }

        return listaUM;
    }

    private ArrayList<Area> getAreaObjetcs() {
        var listaArea = new ArrayList<Area>();
        String tabla = "/areas";
        String json = peticion.sendGet(tabla);
        JSONArray areasJSON = new JSONArray(json);
        for (int i = 0; i < areasJSON.length(); i++) {
            var id = (Integer) areasJSON.getJSONObject(i).get("id");
            var valor = (String) areasJSON.getJSONObject(i).get("nombre");
            var area = new Area(id, valor);
            listaArea.add(area);

        }
        return listaArea;
    }

    private void addDataComboUnidad() {
        getUnidadesMedidaObjetcs().forEach((unidad) -> {
            modelUnidades.addElement(unidad);
        });

    }

    private void addDataComboArea() {
        getAreaObjetcs().forEach((area) -> {
            modelArea.addElement(area);
        });

    }
}
